language: clojure
install: lein all deps
script: lein all test
jdk:
  - oraclejdk7
  - oraclejdk8
  - oraclejdk9
  - oraclejdk10
  - oraclejdk11
  - oraclejdk12
  - oraclejdk-ea
  - oraclejdk-rc
  - oraclejdk-ga
  - openjdk7
  - openjdk8
  - openjdk10
  - openjdk11
  - openjdk12
  - openjdk-ea
  - openjdk-rc
  - openjdk-ga
matrix:
  include:
    - jdk: openjdk9
      before_install:
        - rm "${JAVA_HOME}/lib/security/cacerts"
        - ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"
